"""DataBase creation

Revision ID: 706abdbf33b3
Revises: 
Create Date: 2024-02-22 12:46:47.841586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '706abdbf33b3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stats',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('x', sa.Float(), nullable=False),
                    sa.Column('y', sa.Float(), nullable=False),
                    sa.Column('z', sa.Float(), nullable=False),
                    sa.Column('registered_at', sa.TIMESTAMP(), nullable=True)
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stats')
    # ### end Alembic commands ###
